### ISSUE TITLE
Make InMemoryEntityLookup production code

### ISSUE THREAD

**Issue by JeroenDeDauw** [wmde/WikibaseDataModelServices#29]
This fixture could be made into production code, so it can be used by other components. It's main expected usefulness there is as test fake. Thoughts?

**Comment by JeroenDeDauw** [comment]
@addshore @Benestar thoughts?

**Comment by Benestar** [comment]
Do I understand it right that if it is in the test namespace/folder it cannot be included in other tests outside this component? I think there might be lots of places where this lookup might be useful so I'm not opposed to doing this change.

**Comment by JeroenDeDauw** [comment]
> Do I understand it right that if it is in the test namespace/folder it cannot be included in other tests outside this component?

Yes. Because we only register the autoloader in the test bootstrap: https://github.com/wmde/WikibaseDataModelServices/blob/8a0141eb0b6261c2cbb90e7e815f3db77a0a3439/tests/bootstrap.php#L23-L24

**Comment by thiemowmde** [comment]
+2.
