### ISSUE TITLE
Moving ReferencedEntitiesFinder?

### ISSUE THREAD

**Issue by JeroenDeDauw** [wmde/WikibaseDataModelServices#4]
Originally this (Wikibase Lib) class could be moved to this component without any concerns. However, recently additional stuff was added that makes it bind to `QuantityValue`. If we want to move it like it is now, that mean making this component depend on DataValues Number and other such concrete components. Alternatively the class could be reverted to its original form, moved, and a new one with the added function created that uses the former.

**Comment by thiemowmde** [comment]
Where is this tracked on Phabricator?
