### ISSUE TITLE
ByPropertyIdGrouperTest test failures with php 7

### ISSUE THREAD

**Issue by filbertkm** [wmde/WikibaseDataModelServices#76]
1) Wikibase\DataModel\Services\Tests\ByPropertyIdGrouperTest::testGetByPropertyId with data set #1 (array(Mock_Snak_aa9d5c7d Object (...), Mock_Snak_aa9d5c7d Object (...), Mock_Snak_aa9d5c7d Object (...), Mock_Snak_aa9d5c7d Object (...), Mock_Snak_aa9d5c7d Object (...)), 'P23', array('def'))
Error: Call to a member function getSerialization() on null
/home/travis/build/wmde/WikibaseDataModelServices/src/ByPropertyIdGrouper.php:57
/home/travis/build/wmde/WikibaseDataModelServices/src/ByPropertyIdGrouper.php:52
/home/travis/build/wmde/WikibaseDataModelServices/src/ByPropertyIdGrouper.php:33
/home/travis/build/wmde/WikibaseDataModelServices/tests/unit/ByPropertyIdGrouperTest.php:89
2) Wikibase\DataModel\Services\Tests\ByPropertyIdGrouperTest::testHasPropertyId with data set #1 (array(Mock_Snak_aa9d5c7d Object (...), Mock_Snak_aa9d5c7d Object (...), Mock_Snak_aa9d5c7d Object (...), Mock_Snak_aa9d5c7d Object (...), Mock_Snak_aa9d5c7d Object (...)), 'P23', true)
Error: Call to a member function getSerialization() on null
/home/travis/build/wmde/WikibaseDataModelServices/src/ByPropertyIdGrouper.php:57
/home/travis/build/wmde/WikibaseDataModelServices/src/ByPropertyIdGrouper.php:52
/home/travis/build/wmde/WikibaseDataModelServices/src/ByPropertyIdGrouper.php:33
/home/travis/build/wmde/WikibaseDataModelServices/tests/unit/ByPropertyIdGrouperTest.php:126
3) Wikibase\DataModel\Services\Tests\ByPropertyIdGrouperTest::testHasPropertyId with data set #2 (array(Mock_Snak_aa9d5c7d Object (...), Mock_Snak_aa9d5c7d Object (...), Mock_Snak_aa9d5c7d Object (...), Mock_Snak_aa9d5c7d Object (...), Mock_Snak_aa9d5c7d Object (...)), 'P15', true)
Error: Call to a member function getSerialization() on null
/home/travis/build/wmde/WikibaseDataModelServices/src/ByPropertyIdGrouper.php:57
/home/travis/build/wmde/WikibaseDataModelServices/src/ByPropertyIdGrouper.php:52
/home/travis/build/wmde/WikibaseDataModelServices/src/ByPropertyIdGrouper.php:33
/home/travis/build/wmde/WikibaseDataModelServices/tests/unit/ByPropertyIdGrouperTest.php:126
4) Wikibase\DataModel\Services\Tests\ByPropertyIdGrouperTest::testHasPropertyId with data set #3 (array(Mock_Snak_aa9d5c7d Object (...), Mock_Snak_aa9d5c7d Object (...), Mock_Snak_aa9d5c7d Object (...), Mock_Snak_aa9d5c7d Object (...), Mock_Snak_aa9d5c7d Object (...)), 'P10', true)
Error: Call to a member function getSerialization() on null
/home/travis/build/wmde/WikibaseDataModelServices/src/ByPropertyIdGrouper.php:57
/home/travis/build/wmde/WikibaseDataModelServices/src/ByPropertyIdGrouper.php:52
/home/travis/build/wmde/WikibaseDataModelServices/src/ByPropertyIdGrouper.php:33
/home/travis/build/wmde/WikibaseDataModelServices/tests/unit/ByPropertyIdGrouperTest.php:126
5) Wikibase\DataModel\Services\Tests\ByPropertyIdGrouperTest::testHasPropertyId with data set #4 (array(Mock_Snak_aa9d5c7d Object (...), Mock_Snak_aa9d5c7d Object (...), Mock_Snak_aa9d5c7d Object (...), Mock_Snak_aa9d5c7d Object (...), Mock_Snak_aa9d5c7d Object (...)), 'P11', false)
Error: Call to a member function getSerialization() on null
/home/travis/build/wmde/WikibaseDataModelServices/src/ByPropertyIdGrouper.php:57
/home/travis/build/wmde/WikibaseDataModelServices/src/ByPropertyIdGrouper.php:52
/home/travis/build/wmde/WikibaseDataModelServices/src/ByPropertyIdGrouper.php:33
/home/travis/build/wmde/WikibaseDataModelServices/tests/unit/ByPropertyIdGrouperTest.php:126

**Comment by filbertkm** [comment]
https://travis-ci.org/wmde/WikibaseDataModelServices/jobs/84563783

**Comment by JeroenDeDauw** [comment]
I'm quite confused. This is not happening on master, and I just also pushed a new feature branch on which all is fine: https://travis-ci.org/wmde/WikibaseDataModelServices/builds/84653904

Aude specific failure?

**Comment by JeroenDeDauw** [comment]
Ah... You used some old version of the code. This was fixed in #72
